### ISSUE TITLE
Crash on help page

### ISSUE THREAD

**Issue by rjslater2000** [RLey/wsu-tunnel-app#74] opened 2019-04-11 17:33 UTC
On Chrome mobile, hit help, then rotate the screen and rotate it back. Repeat the rotation a few times. Seems like we're trying to rotate the map but it doesn't exist so it crashes

**Comment by rjslater2000** [comment] 2019-04-11 17:34
![Screenshot_20190411-133000](https://user-images.githubusercontent.com/20517031/55978716-75876700-5c5e-11e9-9519-048dcbe04b3a.jpg)

**Comment by eric-foy** [comment] 2019-04-12 14:59
Changed the help page, can you see if still crashing. New url is http://localhost:3000/ only and help is in an html div tag.

**Comment by tux2603** [comment] 2019-04-13 19:44
The issue is fixed on my phone, which I believe is android lollipop.

**Closed** 2019-04-17 18:34 UTC
Labels: bug
